import 'package:flutter/cupertino.dart';
import 'package:pijjybank/models/category.dart';

class Transaction {
  bool isExpense; //expense if true, else income
  String title;
  double amount;
  String author, party;
  Category category;
  String description;
  DateTime date;

  Transaction(
      {@required this.isExpense,
      @required this.title,
      @required this.amount,
      @required this.author,
      @required this.party,
      @required this.category,
      this.description,
      @required this.date});
}

List<Transaction> transactions = [
  Transaction(
      isExpense: false,
      title: "Party",
      amount: 300,
      author: "Jash",
      party: "Hitansh",
      category: categories[0],
      date: DateTime.now()),
  Transaction(
      isExpense: false,
      title: "Party",
      amount: 300,
      author: "Jash",
      party: "Hitansh",
      category: categories[0],
      date: DateTime.now()),  //DateTime.now().subtract(Duration(days: 1)))
  Transaction(
      isExpense: true,
      title: "birthday",
      amount: 100,
      author: "Jash",
      party: "Chetan",
      category: categories[1],
      date: DateTime.now().subtract(Duration(days: 1))),
  Transaction(
      isExpense: true,
      title: "Party",
      amount: 300,
      author: "Jash",
      party: "Hitansh",
      category: categories[0],
      date: DateTime.now()),
  Transaction(
      isExpense: true,
      title: "Party",
      amount: 300,
      author: "Jash",
      party: "Hitansh",
      category: categories[0],
      date: DateTime.now().subtract(Duration(days: 2))),
  Transaction(
      isExpense: true,
      title: "Party",
      amount: 300,
      author: "Jash",
      party: "Hitansh",
      category: categories[0],
      date: DateTime.now().subtract(Duration(days: 2))),
  Transaction(
      isExpense: true,
      title: "Party",
      amount: 300,
      author: "Jash",
      party: "Hitansh",
      category: categories[0],
      date: DateTime.now().subtract(Duration(days: 2))),
  Transaction(
      isExpense: true,
      title: "Party",
      amount: 300,
      author: "Jash",
      party: "Hitansh",
      category: categories[0],
      date: DateTime.now()),
  Transaction(
      isExpense: true,
      title: "Party",
      amount: 300,
      author: "Jash",
      party: "Hitansh",
      category: categories[0],
      date: DateTime.now()),
  Transaction(
      isExpense: true,
      title: "Party",
      amount: 300,
      author: "Jash",
      party: "Hitansh",
      category: categories[0],
      date: DateTime.now()),
  Transaction(
      isExpense: true,
      title: "Party",
      amount: 300,
      author: "Jash",
      party: "Hitansh",
      category: categories[0],
      date: DateTime.now()),
  Transaction(
      isExpense: true,
      title: "Party",
      amount: 300,
      author: "Jash",
      party: "Hitansh",
      category: categories[0],
      date: DateTime.now().subtract(Duration(days: 3))),
  Transaction(
      isExpense: true,
      title: "Party",
      amount: 300,
      author: "Jash",
      party: "Hitansh",
      category: categories[0],
      date: DateTime.now().subtract(Duration(days: 3))),
  Transaction(
      isExpense: true,
      title: "Party",
      amount: 300,
      author: "Jash",
      party: "Hitansh",
      category: categories[0],
      date: DateTime.now().subtract(Duration(days: 3))),
  Transaction(
      isExpense: true,
      title: "Party",
      amount: 300,
      author: "Jash",
      party: "Hitansh",
      category: categories[0],
      date: DateTime.now().subtract(Duration(days: 3))),
  Transaction(
      isExpense: true,
      title: "Party",
      amount: 300,
      author: "Jash",
      party: "Hitansh",
      category: categories[0],
      date: DateTime.now().subtract(Duration(days: 3))),
  Transaction(
      isExpense: true,
      title: "Party",
      amount: 300,
      author: "Jash",
      party: "Hitansh",
      category: categories[0],
      date: DateTime.now()),
  Transaction(
      isExpense: true,
      title: "Party",
      amount: 300,
      author: "Jash",
      party: "Hitansh",
      category: categories[0],
      date: DateTime.now().subtract(Duration(days: 5))),
  Transaction(
      isExpense: true,
      title: "Party",
      amount: 300,
      author: "Jash",
      party: "Hitansh",
      category: categories[0],
      date: DateTime.now()),
  Transaction(
      isExpense: true,
      title: "Party",
      amount: 300,
      author: "Jash",
      party: "Hitansh",
      category: categories[0],
      date: DateTime.now()),  //DateTime.now().subtract(Duration(days: 1)))
  Transaction(
      isExpense: true,
      title: "birthday",
      amount: 100,
      author: "Jash",
      party: "Chetan",
      category: categories[1],
      date: DateTime.now().subtract(Duration(days: 1))),
  Transaction(
      isExpense: true,
      title: "Party",
      amount: 300,
      author: "Jash",
      party: "Hitansh",
      category: categories[0],
      date: DateTime.now()),
  Transaction(
      isExpense: true,
      title: "Party",
      amount: 300,
      author: "Jash",
      party: "Hitansh",
      category: categories[0],
      date: DateTime.now().subtract(Duration(days: 2))),
  Transaction(
      isExpense: true,
      title: "Party",
      amount: 300,
      author: "Jash",
      party: "Hitansh",
      category: categories[0],
      date: DateTime.now().subtract(Duration(days: 2))),
  Transaction(
      isExpense: true,
      title: "Party",
      amount: 300,
      author: "Jash",
      party: "Hitansh",
      category: categories[0],
      date: DateTime.now().subtract(Duration(days: 2))),
  Transaction(
      isExpense: true,
      title: "Party",
      amount: 300,
      author: "Jash",
      party: "Hitansh",
      category: categories[0],
      date: DateTime.now()),
  Transaction(
      isExpense: true,
      title: "Party",
      amount: 300,
      author: "Jash",
      party: "Hitansh",
      category: categories[0],
      date: DateTime.now()),
  Transaction(
      isExpense: true,
      title: "Party",
      amount: 300,
      author: "Jash",
      party: "Hitansh",
      category: categories[0],
      date: DateTime.now()),
  Transaction(
      isExpense: true,
      title: "Party",
      amount: 300,
      author: "Jash",
      party: "Hitansh",
      category: categories[0],
      date: DateTime.now()),
  Transaction(
      isExpense: true,
      title: "Party",
      amount: 300,
      author: "Jash",
      party: "Hitansh",
      category: categories[0],
      date: DateTime.now().subtract(Duration(days: 3))),
  Transaction(
      isExpense: true,
      title: "Party",
      amount: 300,
      author: "Jash",
      party: "Hitansh",
      category: categories[0],
      date: DateTime.now().subtract(Duration(days: 3))),
  Transaction(
      isExpense: true,
      title: "Party",
      amount: 300,
      author: "Jash",
      party: "Hitansh",
      category: categories[0],
      date: DateTime.now().subtract(Duration(days: 3))),
  Transaction(
      isExpense: true,
      title: "Party",
      amount: 300,
      author: "Jash",
      party: "Hitansh",
      category: categories[0],
      date: DateTime.now().subtract(Duration(days: 3))),
  Transaction(
      isExpense: true,
      title: "Party",
      amount: 300,
      author: "Jash",
      party: "Hitansh",
      category: categories[0],
      date: DateTime.now().subtract(Duration(days: 3))),
  Transaction(
      isExpense: true,
      title: "Party",
      amount: 300,
      author: "Jash",
      party: "Hitansh",
      category: categories[0],
      date: DateTime.now()),
  Transaction(
      isExpense: true,
      title: "Party",
      amount: 300,
      author: "Jash",
      party: "Hitansh",
      category: categories[0],
      date: DateTime.now().subtract(Duration(days: 5))),
];
